baseurl = "http://www.wildernessbushcamp.co.za"
languageCode = "en-gb"
title = "Wilderness Bushcamp"
theme = "wilderness-bushcamp"
metaDataFormat = "toml"
version = "0.0.1"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params.css]
  main = ["style.css"]

[params.js]
  main = ["scripts.js"]

[params.js.accommodation]
  single = ["jquery-3.2.1.min.js", "jquery.fancybox.min.js", "scripts.js", "gallery.js"]

[menu]

  [[menu.main]]
  identifier = "accommodation"
  url = "/accommodation"
  name = "Accommodation"
  weight = 1.0

  [[menu.main]]
  url = "/the-lapa"
  name = "The Lapa"
  weight = 2.0

  [[menu.main]]
  url = "/rates-and-bookings"
  name = "Rates & Bookings"
  weight = 3.0

  [[menu.main]]
  url = "/things-to-do"
  name = "Things to do"
  weight = 4.0

  [[menu.main]]
  url = "/contact-us"
  name = "Contact Us"
  weight = 5.0

  [[menu.social]]
  identifier = "facebook"
  url = "https://www.facebook.com/therealwildernessbushcamp"
  weight = 1

  [[menu.social]]
  identifier = "instagram"
  url = "https://www.instagram.com/wildernessbushcamp"
  weight = 2

  [[menu.social]]
  identifier = "tripadvisor"
  url = "http://www.tripadvisor.com/Hotel_Review-g312610-d1161107-Reviews-Wilderness_Bushcamp-Wilderness_Western_Cape.html"
  weight = 3

  [[menu.footer]]
  identifier = "phone"
  name = "044 877 1168"
  weight = 1.0

  [[menu.footer]]
  identifier = "email"
  name = "info@wildernessbushcamp.co.za"
  url = "mailto:info@wildernessbushcamp.co.za"
  weight = 2.0

  [[menu.footer]]
  identifier = "mobile"
  name = "078 419 2021"
  weight = 3.0

 