baseurl: 'https://wildernessbushcamp.co.za'
languageCode: en-gb
title: Wilderness Bushcamp
metaDataFormat: "yml"
version: "1.6.1"
theme: 
  - local
  - github.com/andrew-paterson/pandago

module:
  imports:
    - path: github.com/andrew-paterson/hugo-sundries
      disabled: false
      mounts:
        - source: partials
          target: layouts/partials/hugo-sundries
        - source: shortcodes
          target: layouts/shortcodes
        - source: scss
          target: assets/scss/hugo-sundries
        - source: js
          target: assets/js/hugo-sundries

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: accommodation
      url: /accommodation
      name: Accommodation
      weight: 1
    - url: /the-lapa
      name: The Lapa
      weight: 2
    - url: /rates-and-bookings
      name: Rates
      weight: 3
    - url: /things-to-do
      name: Things to do
      weight: 5
    - url: /media
      name: Media
      weight: 6
    - url: /contact-us
      name: Contact
      weight: 7
    - url: /covid-19
      name: COVID-19
      weight: 8
 
params:
  image_dir: /media/images
